version: '3.5'

networks:
  prefect:
    name: prefect


services:
  # --------------------------------------#
  #               Postgres                #
  # --------------------------------------#
  postgres:
    image: postgres:14
    command:
      - postgres
      - -c
      - max_connections=150
    environment:
      POSTGRES_USER: prefect
      POSTGRES_PASSWORD: test-password
      POSTGRES_DB: prefect_server
    healthcheck:
      interval: 10s
      retries: 60
      start_period: 2s
      test: pg_isready -q -d $${POSTGRES_DB} -U $${POSTGRES_USER} | grep "accepting connections" || exit 1
      timeout: 20s
    ports:
    - published: 5433
      target: 5432
    restart: on-failure
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    networks:
      - prefect
  # --------------------------------------#
  #             Prefect Server            #
  # --------------------------------------#
  prefect-server:
    image: prefect:2.14.15
    command:
      - prefect
      - server
      - start
    ports:
      - 4200:4200
    depends_on:
     postgres:
       condition: service_started
    volumes:
      - ${PWD}/volumes/prefect:/root/.prefect
      - ${PWD}/flows:/flows
    environment:
      PREFECT_SERVER_API_HOST: 0.0.0.0
      PREFECT_API_DATABASE_CONNECTION_URL: postgresql+asyncpg://prefect:test-password@postgres:5432/prefect_server
      # PREFECT_ORION_DATABASE_CONNECTION_URL: postgresql+asyncpg://user_prefect:Nr19*04E!*v8&A&rkWQ@10.5.0.4:5432/prefectdb
      PREFECT_ORION_ANALYTICS_ENABLED: "false"
      PREFECT_LOGGING_SERVER_LEVEL: WARNING
      PREFECT_API_URL: http://prefect-server:4200/api
      # PREFECT_API_URL: https://automation.amoga.app/api
    networks:
      - prefect
  # --------------------------------------#
  #             Docker Agent              #
  # --------------------------------------#
  prefect-agent:
    image: prefect:2.14.15
    command:
      - prefect
      - agent
      - start
      - -q
      - default
    depends_on:
      prefect-server:
        condition: service_started
    environment:
      PREFECT_API_URL: http://prefect-server:4200/api
      PREFECT_LOGGING_LEVEL: DEBUG
      PREFECT_AGENT_QUERY_INTERVAL: 30.0
      DOCKER_HOST: unix://var/run/docker.sock
    volumes:
      - ${PWD}/gsheet_data:/gsheet_data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - prefect
